# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

    config.vm.define "web" do |web|
        web.vm.box = "centos-7.2"
        web.vm.network "forwarded_port", guest: 80, host: 8081
        web.vm.network "private_network", ip: "192.168.10.100"
        web.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision/playbook.yaml"
        end
    end

    config.vm.define "mon" do |mon|
        mon.vm.box = "centos-7.2"
        mon.vm.network "forwarded_port", guest: 80, host: 8082
        mon.vm.network "private_network", ip: "192.168.10.101"
        mon.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision/nagios.yaml"
        end
    end





    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--memory", "256"]
   end
end
