# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y httpd
    sudo chkconfig httpd on
    sudo service httpd start
    sudo echo "Hello World" > /var/www/html/index.html
  SHELL
end
