# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|


    config.vm.define "worker1" do |worker1|
        worker1.vm.box = "bento/ubuntu-22.04"
        worker1.vm.network "private_network", ip: "192.168.10.101"
    end

    config.vm.define "worker2" do |worker2|
        worker2.vm.box = "bento/ubuntu-22.04"
        worker2.vm.network "private_network", ip: "192.168.10.102"
    end

    config.vm.define "master" do |master|
        master.vm.box = "bento/ubuntu-22.04"
        master.vm.network "private_network", ip: "192.168.10.100"
        master.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "provisioning/ansible.yaml"
          ansible.inventory_path = "provisioning/inventory"
          ansible.config_file = "provisioning/ansible.cfg"
          ansible.verbose = true
          ansible.limit = "all"
        end
    end

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
   end
end
