- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: Creating a file with content
  become: yes
  copy:
    dest: "/etc/sudoers.d/ansibleuser"
    content: |
      "{{ ansible_user }}" ALL=(ALL) NOPASSWD:ALL
