- hosts: all
  become: yes
  roles:
    - server
    - mysql
    - php
    - wordpress
    - nagios-nrpe
  vars:
    mysql_root_password:
    wp_mysql_password: wpUserP2$$w0rd
    mon_mysql_password: m0nUserP2$$w0rd
    nagios_server: 192.168.10.101
